version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile_api_gateway
    restart: always
    ports:
      - "5000:5000"
    networks:
      - backend

  ia_container:
    build:
      context: .
      dockerfile: Dockerfile_ia_container
    restart: always
    ports:
      - "5001:5001"
    networks:
      - backend

networks:
  backend:
    driver: bridge