version: '3.8'

services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - backend

  ia_container:
    build:
      context: ./PxCara_Finalizado
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    networks:
      - backend

networks:
  backend:
    driver: bridge