FROM python:3.11

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libhdf5-dev \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN mkdir -p /app/shared

COPY ./modelos/yolov8n-face.pt /app/shared
COPY ./modelos/modelo_mnet.keras /app/shared

RUN pip install -r ./PxCara_Finalizado/requirements.txt

EXPOSE 5001

CMD ["python", "./PxCara_Finalizado/PxCara_Modelo.py"]